# Generated by Django 2.2.15 on 2020-09-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniprotkb',
            name='gene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Gene'),
            preserve_default=False,
        ),
    ]
